EPHARMA/Models/Pharmacy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EPHARMA.Models
{
    public class Pharmacy
    {
        [Key]
        public int PharmacyId { get; set; }
        public int? DeliveryCharges { get; set; }
        [Required]
        [Display(Name = "City")]
        public int CityId { get; set; }
        [ForeignKey("CityId")]
        public virtual City Cities { get; set; }
        [Required]
        [Display(Name = "Vendor")]
        public int VendorId { get; set; }
        [ForeignKey("VendorId")]
        public virtual Vendor Vendors { get; set; }
        [Display(Name = "Pharmacy Name")]
        public string PharmacyName { get; set; }
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
        public string Contact { get; set; }
        public bool OnlineStatus { get; set; } = true;
        public string PharmacyLocation { get; set; }
        public string PharmacyAddress { get; set; }
        [Display(Name = "Latitude")]
        public double PharmacyLatitude { get; set; }
        [Display(Name = "Longitude")]
        public double PharmacyLongitude { get; set; }
        public string CoverImage { get; set; }
        public string PharmacyLogo { get; set; }
        public string Overview { get; set; }
        public bool IsBestRated { get; set; } = true;
        public bool IsFeatured { get; set; } = true;
        public bool Status { get; set; } = true;
        public DateTime Date { get; set; } = getDate();
        public static DateTime getDate()
        {
            DateTime date1 = DateTime.UtcNow;
            TimeZoneInfo tz = TimeZoneInfo.FindSystemTimeZoneById("Pakistan Standard Time");
            DateTime date2 = TimeZoneInfo.ConvertTime(date1, tz);
            return date2;
        }
    }
}

EPHARMA/Controllers/PharmacyController.cs
using EPHARMA.Data;
using EPHARMA.Models;
using EPHARMA.Services;
using EPHARMA.Services.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EPHARMA.Controllers
{
    public class PharmacyController : Controller
    {
        private readonly IImageInterface _imageService;
        private readonly ApplicationDbContext _context;
        private Pharmacy _pharmacy;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private string UserId;
        public PharmacyController(ApplicationDbContext Context,
            IImageInterface ImageService, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _imageService = ImageService;
            _context = Context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var AllPharmacies = _context.Pharmacies.Include(a => a.Vendors);
            return View(AllPharmacies);
        }

        public async Task<IdentityResult> MakeIdentity(string Email, string Password, string Role)
        {
            try
            {

                if (_roleManager != null)
                {
                    if (!await _roleManager.RoleExistsAsync(Role))
                    {
                        await _roleManager.CreateAsync(new IdentityRole(Role));
                    }
                }

                var user = new IdentityUser { UserName = Email, Email = Email, EmailConfirmed = true };
                //    Password = "Ali@123*";
                var result = await _userManager.CreateAsync(user, Password);
                if (result.Succeeded)
                {

                    //_logger.LogInformation("User created a new account with password.");
                    try
                    {
                        await _userManager.AddToRoleAsync(user, Role);
                    }
                    catch (Exception e)
                    {
                        return null;
                    }
                    return result;
                }
                else
                {
                    return result;
                }
            }
            catch (Exception e)
            {
                return null;
            }

        }


        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.CityId = new SelectList(_context.Cities.Where(x => x.Status), "CityId", "CityName");
            ViewBag.VendorId = new SelectList(_context.Vendors.Where(x => x.Status), "VendorId", "VendorName");
            if (id == 0)
            {
                _pharmacy = new Pharmacy();
            }
            else
            {
                _pharmacy = _context.Pharmacies.Include(v => v.Vendors).Where(x => x.PharmacyId==id).FirstOrDefault();
            }
            return View(_pharmacy);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Pharmacy pharmacy, IFormFile PharmacyLogo, IFormFile CoverImage)
        {
            //UserId = HttpContext.Session.GetObject<string>("UserId");
            string uniqueFileName;
            if (pharmacy.PharmacyId == 0)
            {
                var result = await MakeIdentity(pharmacy.Vendors.VendorEmail, pharmacy.Vendors.Password, "Vendor");
                if (result.Succeeded != true)
                {

                    return View(pharmacy);
                }


                uniqueFileName = _imageService.AddImage(PharmacyLogo);
                pharmacy.PharmacyLogo = uniqueFileName;
                uniqueFileName = _imageService.AddImage(CoverImage);
                pharmacy.CoverImage = uniqueFileName;
                _context.Vendors.Add(pharmacy.Vendors);
                pharmacy.VendorId = pharmacy.Vendors.VendorId;
                _context.Pharmacies.Add(pharmacy);
                _context.SaveChanges();
            }
            else
            {
                if (PharmacyLogo != null) //Logo is edited(changed)
                {
                    _imageService.RemoveImage(pharmacy.PharmacyLogo);
                    uniqueFileName = _imageService.AddImage(PharmacyLogo);
                    pharmacy.PharmacyLogo = uniqueFileName;
                }
                if (CoverImage != null)//image is edited(changed)
                {
                    _imageService.RemoveImage(pharmacy.CoverImage);
                    uniqueFileName = _imageService.AddImage(CoverImage);
                    pharmacy.CoverImage = uniqueFileName;
                }
                pharmacy.Vendors.VendorId =pharmacy.VendorId ;
                _context.Entry(pharmacy).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _context.SaveChanges();
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public async Task<JsonResult> ChangePharmacyStatus(int id)
        {
            var doc = _context.Pharmacies.Find(id);
            doc.Status = !doc.Status;
            _context.SaveChanges();
            return Json("Success");
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var pharmacy = _context.Pharmacies.Find(id);
            if (pharmacy == null)
            {
                return NotFound();
            }
            pharmacy.Status = false;
            _context.Entry(pharmacy).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

EPHARMA/Views/Pharmacy/Index.cshtml
@model IEnumerable<EPHARMA.Models.Pharmacy>

@{
    ViewData["Title"] = "Index";
}
<div class="app-content">
    <div class="content-wrapper">
        <div class="content-header row">
            <h4 class="card-title">Pharmacy</h4>
            <a asp-action="Create">
                <button class="btn btn-primary mb-2 d-flex align-items-center" style="margin-left:650px">
                    <i class="bx bx-plus"></i>&nbsp; Add new Pharmacy
                </button>
            </a>
        </div>
        <div class="content-body">
            <div class="users-list-table">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table zero-configuration">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.PharmacyLogo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.PharmacyName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.VendorId)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Email)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.Status)
                                        </th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            <img src="~/images/@item.PharmacyLogo"
                                                 class="rounded-lg"
                                                 height="50" width="50"
                                                 asp-append-version="true" />
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PharmacyName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Vendors.VendorName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>

                                        <td>
                                            @if (item.Status == true)
                                            {
                                                <div style="color:green">Active</div>
                                            }
                                            else
                                            {
                                                <div style="color:red">Deactive</div>
                                            }

                                        </td>
                                      

                                        <td>
                                            <div class="fonticon-container">
                                                <div class="fonticon-wrap" style="margin-bottom: 0px;">
                                                    <i onclick="@("window.location.href='" + @Url.Action("Create", "Pharmacy", new {id = item.PharmacyId}) + "'");" class="bx bx-edit"></i>
                                                </div>
                                            </div>
                                           
                                         

                                         

                                            @if (!item.Status)
                                            {
                                                <div class="fonticon-container">
                                                    <div class="fonticon-wrap" style="margin-bottom: 0px;">
                                                        <i onclick="ChangePharmacyStatus(@item.PharmacyId)" class="bx bx-power-off"></i>
                                                    </div>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="fonticon-container">
                                                    <div class="fonticon-wrap" style="margin-bottom: 0px;">
                                                        <i onclick="ChangePharmacyStatus(@item.PharmacyId)" class="bx bx-power-off"></i>
                                                    </div>
                                                </div>
                                            }

                                        </td>

                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function ChangePharmacyStatus(id) {
        $.ajax({
            type: "Get",
            url: '/Pharmacy/ChangePharmacyStatus',
            data: { id: id },
            success: function (json) {
                if (json == "Success") {
                    //swal("Updated!", "Customer Status Updated!", "success");
                    window.location.reload();
                }


                // swal("Updated!", "Customer Status Updated!", "success");
                //window.location.reload();
            },
            error: function (xhr) {
                //  swal("Error", "Please Try again later!", "error");
            }
        });
    }
    </script>