EPHARMA/Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EPHARMA.Models
{
    public class Appointment
    {
        [Key]
        public int AppointmentId { get; set; }
        [Required]
        [Display(Name = "Customer")]
        public int CustomerId { get; set; }
        [ForeignKey("CustomerId")]
        public virtual Customer Customers { get; set; }
        [Required]
        [Display(Name = "Doctor")]
        public int DoctorId { get; set; }
        [ForeignKey("DoctorId")]
        public virtual Doctor Doctors { get; set; }
        public string AppointmentCode { get; set; }
        public string AppointmentStatus { get; set; }
        public string AppointmentDay{ get; set; }
        public bool IsFinished { get; set; } = false;
        public DateTime AppointmentDate { get; set; } = getDate();
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Prescription { get; set; }
        public bool HasPrescription { get; set; } = false;
        public int NumberOfSlots { get; set; }
        public bool Status { get; set; } = true;
        public DateTime Date { get; set; } = getDate();
        public static DateTime getDate()
        {
            DateTime date1 = DateTime.UtcNow;
            TimeZoneInfo tz = TimeZoneInfo.FindSystemTimeZoneById("Pakistan Standard Time");
            DateTime date2 = TimeZoneInfo.ConvertTime(date1, tz);
            return date2;
        }
    }
}

EPHARMA/Controllers/AppointmentController.cs
using EPHARMA.Data;
using EPHARMA.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EPHARMA.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private Appointment _appointment;
        private readonly UserManager<IdentityUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;
        public AppointmentController(ApplicationDbContext Context, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = Context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        [Authorize(Roles = "Admin,Doctor")]
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            var role = await _userManager.GetRolesAsync(user);
            if (role.ElementAt(0) == "Admin")
            {
                var AllAppointments = _context.Appointments.Include(d => d.Doctors).Where(x => x.Status);
                return View(AllAppointments);
            }
            else {
                var doc = _context.Doctors.Where(a => a.DoctorEmail == user.Email).FirstOrDefault();
                if (doc != null)
                {
                    var AllAppointments = _context.Appointments.Include(d => d.Doctors).Where(x => x.Status && x.DoctorId == doc.DoctorId);
                    return View(AllAppointments);
                }
                else
                {
                    return View(null);
                }
            }
        }

        
        public IActionResult Create(int id)
        {
            ViewBag.CustomerId = new SelectList(_context.Customers.Where(x => x.Status), "CustomerId", "CustomerName");
            ViewBag.DoctorId = new SelectList(_context.Doctors.Where(x => x.Status), "DoctorId", "DoctorName");
            if (id == 0)
            {
                _appointment = new Appointment();
            }
            else
            {
                _appointment = _context.Appointments.Find(id);
            }
            return View(_appointment);
        }
        [HttpPost]
        public IActionResult Create(Appointment NewAppointment)
        {
            if (NewAppointment.AppointmentId == 0)
            {
                _context.Appointments.Add(NewAppointment);
            }
            else
            {
                _context.Entry(NewAppointment).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult CreatePrescription(int id)
        {
            ViewBag.CustomerId = new SelectList(_context.Customers.Where(x => x.Status), "CustomerId", "CustomerName");
            ViewBag.DoctorId = new SelectList(_context.Doctors.Where(x => x.Status), "DoctorId", "DoctorName");
            if (id == 0)
            {
                _appointment = new Appointment();
            }
            else
            {
                _appointment = _context.Appointments.Include(c => c.Customers).Include(d => d.Doctors).Where(d => d.AppointmentId == id).FirstOrDefault();
            }
         //   ViewBag.Editortext = "<p><strong>Patient Name:&nbsp;</strong>"+_appointment.Customers.CustomerName+"</p><p><strong> Patient Age: &nbsp;</strong>"+ _appointment.Customers.Age+"</p><p><strong> Date:&nbsp;</strong>"+DateTime.Now.Date.ToShortDateString()+"</p><p><strong> Doctor:&nbsp;</strong>"+_appointment.Doctors.DoctorName+"</p><p> &nbsp;</p> ";
            return View(_appointment);
        }
        [HttpPost]
        public IActionResult CreatePrescription(int id, string editortext)
        {
            _appointment = _context.Appointments.Include(c => c.Customers).Include(d => d.Doctors).Where(d => d.AppointmentId == id).FirstOrDefault();
           var PreText = "<p><strong>Patient Name:&nbsp;</strong>" + _appointment.Customers.CustomerName + "</p><p><strong> Patient Age: &nbsp;</strong>" + _appointment.Customers.Age + "</p><p><strong> Date:&nbsp;</strong>" + DateTime.Now.Date.ToShortDateString() + "</p><p><strong> Doctor:&nbsp;</strong>" + _appointment.Doctors.DoctorName + "</p><p> &nbsp;</p> ";
            _appointment.HasPrescription = true;
            _appointment.Prescription = PreText + editortext;
            _context.Appointments.Update(_appointment);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var doctor = _context.Doctors.Where(x => x.DoctorId == id);
            foreach (var item in doctor)
            {
                item.Status = false;
                _context.Entry(item).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            }
            var appointment = _context.Appointments.Find(id);
            if (appointment == null)
            {
                return NotFound();
            }
            appointment.Status = false;
            _context.Entry(appointment).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

EPHARMA/Views/Appointment/Create.cshtml
@model EPHARMA.Models.Appointment

@{
    ViewData["Title"] = "Create";
}
<section id="multiple-column-form">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">@(Model.AppointmentId ==0 ? "Create Appointment" : "Edit Appointment")</h2>
                </div>
                <div class="card-body">
                    <form asp-action="Create">
                        <input type="hidden" asp-for="AppointmentId" />
                        <input type="hidden" asp-for="Date" />

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row clearfix">
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label asp-for="AppointmentCode" class="control-label"></label>
                                    <input asp-for="AppointmentCode" class="form-control" />
                                    <span asp-validation-for="AppointmentCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label asp-for="Customers.CustomerName" class="control-label"></label>
                                    <input asp-for="Customers.CustomerName" class="form-control" />
                                    <span asp-validation-for="Customers.CustomerName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label asp-for="Doctors.DoctorName" class="control-label"></label>
                                    <input asp-for="Doctors.DoctorName" class="form-control" />
                                    <span asp-validation-for="Doctors.DoctorName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="AppointmentStatus" class="control-label"></label>
                                    <input asp-for="AppointmentStatus" class="form-control" />
                                    <span asp-validation-for="AppointmentStatus" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label asp-for="StartTime" class="control-label"></label>
                                    <input asp-for="StartTime" class="form-control" />
                                    <span asp-validation-for="StartTime" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label asp-for="EndTime" class="control-label"></label>
                                    <input asp-for="EndTime" class="form-control" />
                                    <span asp-validation-for="EndTime" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <label asp-for="NumberOfSlots" class="control-label"></label>
                                    <input asp-for="NumberOfSlots" class="form-control" />
                                    <span asp-validation-for="NumberOfSlots" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <button id="SubmitButton" type="submit" class="btn btn-primary btn-round">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

EPHARMA/Views/Appointment/CreatePrescription.cshtml
@model EPHARMA.Models.Appointment
@{
    ViewData["Title"] = "CreatePrescription";
}

<form asp-action="CreatePrescription">
    <div class="row clearfix">
        <input type="hidden" name="id" value="@Model.AppointmentId" asp-for="AppointmentId" />
        <div class="col-sm-6">
            <div class="form-group">
                <label asp-for="Customers.CustomerName" class="control-label">Customer Name</label>
                <input asp-for="Customers.CustomerName" class="form-control" readonly />
                <span asp-validation-for="Customers.CustomerName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label asp-for="Doctors.DoctorName" class="control-label">Doctor Name</label>
                <input asp-for="Doctors.DoctorName" class="form-control" readonly />
                <span asp-validation-for="Doctors.DoctorName" class="text-danger"></span>
            </div>
        </div>
    </div>
<textarea class="ckeditor" name="editortext"></textarea>
    <button id="SubmitButton" type="submit" class="btn btn-primary btn-round">Submit</button>
</form>


@section Scripts {
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('CkEditorText')
        });
    </script>
}

EPHARMA/Views/Appointment/Index.cshtml
@model IEnumerable<EPHARMA.Models.Appointment>

@{
    ViewData["Title"] = "Index";
}
<div class="app-content">
    <div class="content-wrapper">
        <div class="content-header row">
            <h4 class="card-title">Appointment</h4>
            
        </div>
        <div class="content-body">
            <div class="users-list-table">
                <div class="card">
                    <div class="card-body">
                        @*<div class="card-header">
                                <h4 class="card-title">City Details</h4>
                                <a asp-action="Create">
                                    <button id="addRow" class="btn btn-primary mb-2 d-flex align-items-center">
                                        <i class="bx bx-plus"></i>&nbsp; Add new City
                                    </button>
                                </a>
                            </div>*@
                        <div class="table-responsive">
                            <table class="table zero-configuration">
                                <thead>
                                    <tr>
                                        <th>
                                            Appointment Code
                                        </th>
                                        <th>
                                            Doctor
                                        </th>
                                        <th>
                                            Appointment Status
                                        </th>
                                        <th>
                                            Start Time
                                        </th>
                                        <th>
                                            End Time
                                        </th>
                                                                             
                                        <th>
                                            Appointment Date
                                        </th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AppointmentCode)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Doctors.DoctorName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AppointmentStatus)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StartTime)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EndTime)
                                        </td>
                                       
                                        <td>
                                            @*@Html.DisplayFor(modelItem => item.AppointmentDate)*@
                                           @item.AppointmentDay, @item.AppointmentDate.ToShortDateString()
                                        </td>
                                       
                                        <td class=" mt-3">
                                            @if (!item.HasPrescription)
                                            {
                                                <div class="fonticon-container">
                                                    <div class="fonticon-wrap" style="margin-bottom: 0px;">
                                                        <i onclick="@("window.location.href='" + @Url.Action("CreatePrescription", "Appointment", new {id = item.AppointmentId}) + "'");" class="bx bx-edit"></i>
                                                    </div>
                                                </div>
                                                }
                                            </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>